menu:
- {name: 'blog', url: '/blog'}
- {name: 'people', url: '/people'}
- {name: 'about', url: '/about'}

people:
- {name: 'Mengyang Gu', title: 'Professor', department: 'Statistics and Applied Probability', institution: 'University of California Santa Barbara', email: 'test@ucsb.edu', image: 'assets/img/gu.jpg', url: 'Mengyang-Gu'}
- {name: 'Sui Tang', title: 'Professor', department: 'Mathematics', institution: 'University of California Santa Barbara',email: 'test@ucsb.edu', image: 'assets/img/Sui.jpg', url: 'Sui-Tang'}
- {name: 'Xinyi Fang', title: 'Graduate Student', department: 'Statistics and Applied Probability', institution: 'University of California Santa Barbara', email: 'test@ucsb.edu', image: 'assets/img/Xinyi.jpg', url: 'Xinyi-Fang'}
- {name: 'Xubo Liu', title: 'Graduate Student', department: 'Statistics and Applied Probability', institution: 'University of California Santa Barbara', email: 'test@ucsb.edu', image: 'assets/img/xubo.JPG', url: 'Xubo-Liu'}
- {name: 'Erika McPhillips', title: 'Graduate Student', department: 'Statistics and Applied Probability', institution: 'University of California Santa Barbara', email: 'test@ucsb.edu', image: 'assets/img/erika.png', url: 'Erika-McPhillips'}

contacts:
- {name: 'Mengyang Gu', title: 'Professor', department: 'Statistics and Applied Probability', institution: 'University of California Santa Barbara', email: 'test@ucsb.edu', image: 'assets/img/contact.jpg'}
